OnDoanThuan/CNPMNC_Giao/CNPMNC_Giao/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_Giao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
            this.KichCoes = new HashSet<KichCo>();
            this.LichSuGiamGiaSanPhams = new HashSet<LichSuGiamGiaSanPham>();
            this.LichSuGiaSanPhams = new HashSet<LichSuGiaSanPham>();
            this.MauSacs = new HashSet<MauSac>();
            this.SanPhamYeuThiches = new HashSet<SanPhamYeuThich>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public int GiaTienMoi { get; set; }
        public int GiaTienCu { get; set; }
        public string MoTa { get; set; }
        public string AnhSP { get; set; }
        public int MaVatLieu { get; set; }
        public int MaDanhMuc { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int MaNhaCungCap { get; set; }

        // Thuộc tính mới để theo dõi số lượt xem chi tiết
        public int SoLuotXem { get; set; } = 0;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KichCo> KichCoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiamGiaSanPham> LichSuGiamGiaSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaSanPham> LichSuGiaSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauSac> MauSacs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual VatLieu VatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamYeuThich> SanPhamYeuThiches { get; set; }
    }
}

OnDoanThuan/CNPMNC_Giao/CNPMNC_Giao/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CNPMNC_Giao.Models;

namespace CNPMNC_Giao.Areas.Admin.Controllers
{
    public class SanPhamsController : Controller
    {
        private DAPM_1Entities1 db = new DAPM_1Entities1();

        // GET: Admin/SanPhams
        public ActionResult Index(string searchString)
        {
            // Lấy danh sách sản phẩm, bao gồm các bảng liên kết (DanhMuc, NhaCungCap, VatLieu)
            var sanPhams = db.SanPham.Include(s => s.DanhMuc)
                                     .Include(s => s.NhaCungCap)
                                     .Include(s => s.VatLieu);

            // Nếu có chuỗi tìm kiếm, lọc sản phẩm theo tên, danh mục, nhà cung cấp
            if (!string.IsNullOrEmpty(searchString))
            {
                sanPhams = sanPhams.Where(s => s.TenSanPham.Contains(searchString) ||
                                               s.DanhMuc.TenDanhMuc.Contains(searchString) ||
                                               s.NhaCungCap.TenNhaCungCap.Contains(searchString) ||
                                               s.VatLieu.TenVatlieu.Contains(searchString));
            }

            // Trả về danh sách sản phẩm sau khi lọc (nếu có)
            return View(sanPhams.ToList());
        }

        // GET: Admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            var kichCos = sanPham.KichCoes.ToList();

            // Gửi thông tin đến view
            ViewBag.KichCos = kichCos;

            //ViewBag.KichCos = new SelectList(sanPham.KichCo, "MaKichCo", "SoKichCo"); // Giả định "SoKichCo" là tên hiển thị


            return View(sanPham);

        }

        // GET: Admin/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaDanhMuc = new SelectList(db.DanhMuc, "MaDanhMuc", "TenDanhMuc");
            ViewBag.MaNhaCungCap = new SelectList(db.NhaCungCap, "MaNhaCungCap", "TenNhaCungCap");
            ViewBag.MaVatLieu = new SelectList(db.VatLieu, "MaVatLieu", "TenVatlieu");


            var sanPham = new SanPham
            {
                NgayTao = DateTime.Now.Date //Ngày Tạo là ngày hôm nay
            };

            return View(sanPham);

        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,GiaTienMoi,GiaTienCu,MoTa,AnhSP,MaVatLieu,MaDanhMuc,NgayTao,MaNhaCungCap")] SanPham sanPham, HttpPostedFileBase AnhSanPham)
        {
            if (ModelState.IsValid)
            {
                var idImage = Guid.NewGuid().ToString();
                string _FileName = "";
                int index = AnhSanPham.FileName.IndexOf('.');
                _FileName = idImage.ToString() + "." + AnhSanPham.FileName.Substring(index + 1);
                string path1 = Path.Combine(Server.MapPath("~/AnhSanPham"), _FileName);
                AnhSanPham.SaveAs(path1);
                sanPham.AnhSP = _FileName;


                // Nếu Ngày Tạo chưa được gán, thiết lập nó là ngày hôm nay
                if (sanPham.NgayTao == default(DateTime))
                {
                    sanPham.NgayTao = DateTime.Now.Date; 
                }
               

                db.SanPham.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDanhMuc = new SelectList(db.DanhMuc, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            ViewBag.MaNhaCungCap = new SelectList(db.NhaCungCap, "MaNhaCungCap", "TenNhaCungCap", sanPham.MaNhaCungCap);
            ViewBag.MaVatLieu = new SelectList(db.VatLieu, "MaVatLieu", "TenVatlieu", sanPham.MaVatLieu);

            return View(sanPham);
        }

        // GET: Admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Tìm sản phẩm theo ID
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }

            // Tạo các danh sách cho dropdown
            ViewBag.MaDanhMuc = new SelectList(db.DanhMuc, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            ViewBag.MaNhaCungCap = new SelectList(db.NhaCungCap, "MaNhaCungCap", "TenNhaCungCap", sanPham.MaNhaCungCap);
            ViewBag.MaVatLieu = new SelectList(db.VatLieu, "MaVatLieu", "TenVatlieu", sanPham.MaVatLieu);



            return View(sanPham);
        }

        // POST: Admin/SanPhams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,GiaTienMoi,GiaTienCu,MoTa,AnhSP,MaVatLieu,MaDanhMuc,NgayTao,MaNhaCungCap")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Tạo lại danh sách cho dropdown nếu ModelState không hợp lệ
            ViewBag.MaDanhMuc = new SelectList(db.DanhMuc, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            ViewBag.MaNhaCungCap = new SelectList(db.NhaCungCap, "MaNhaCungCap", "TenNhaCungCap", sanPham.MaNhaCungCap);
            ViewBag.MaVatLieu = new SelectList(db.VatLieu, "MaVatLieu", "TenVatlieu", sanPham.MaVatLieu);



            return View(sanPham);
        }


        // GET: Admin/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPham.Find(id);
            db.SanPham.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //=========================
        // GET: Admin/SanPhams/TaoKichCo
        // GET: Admin/SanPhams/TaoKichCo
        public ActionResult TaoKichCo()
        {
            ViewBag.SanPhams = db.SanPham.ToList(); // Lấy danh sách sản phẩm
            return View(new KichCo());
        }

        // POST: Admin/SanPhams/TaoKichCo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TaoKichCo(KichCo kichCoViewModel)
        {
            if (ModelState.IsValid)
            {
                var kichCo = new KichCo
                {
                    MaSanPham = kichCoViewModel.MaSanPham,
                    SoKichCo = kichCoViewModel.SoKichCo,
                    SoLuong = kichCoViewModel.SoLuong
                };

                db.KichCo.Add(kichCo);
                db.SaveChanges();
                return RedirectToAction("Index"); // Redirect đến trang danh sách sản phẩm hoặc kích cỡ
            }

            // Nếu ModelState không hợp lệ, cần phải lấy lại danh sách sản phẩm
            ViewBag.SanPhams = db.SanPham.ToList(); // Lấy lại danh sách sản phẩm nếu có lỗi
            return View(kichCoViewModel);
        }

    }
}

OnDoanThuan/CNPMNC_Giao/CNPMNC_Giao/Areas/Admin/Views/SanPhams/Create.cshtml
@model CNPMNC_Giao.Models.SanPham

@{
    ViewBag.Title = "Create";
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>


<h2 class="page-title">Tạo Sản Phẩm Mới</h2>

@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thông Tin Sản Phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">

            @Html.LabelFor(model => model.TenSanPham, "Tên sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(model => model.GiaTienMoi, "Giá tiền mới", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GiaTienMoi, new { htmlAttributes = new { @class = "form-control", type = "number", min = "1" } })
                    @Html.ValidationMessageFor(model => model.GiaTienMoi, "", new { @class = "text-danger" })
                </div>
            </div>
        }
            <div class="form-group">
                @Html.LabelFor(model => model.GiaTienCu, "Giá tiền cũ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GiaTienCu, new { htmlAttributes = new { @class = "form-control", type = "number", min = "1" } })
                    @Html.ValidationMessageFor(model => model.GiaTienCu, "", new { @class = "text-danger" })
                </div>
            </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, "Mô Tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.AnhSP, "Ảnh sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="ImageFile" type="file" } />
                </div>
            </div>*@
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh </label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="AnhSanPham" type="file" } />
            </div>
        </div>
        @*<div class="form-group">
                @Html.Label("ImageFile", "Hình ảnh", new { @class = "control-label col-md-2" })
                <div class="col-md-10 input-group full-width">
                    <input type="file" name="ImageFile" class="form-control full-width no-max-width" />
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.MaVatLieu, "Vật Liệu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaVatLieu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaVatLieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, "Danh Mục", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.NgayTao, "Ngày tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.NgayTao,
                                     "{0:yyyy-MM-dd}",
                                     new { @class = "form-control", type = "date", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
                </div>
            </div>*@



        <div class="form-group">
            @Html.LabelFor(model => model.MaNhaCungCap, "Nhà Cung Cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNhaCungCap", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhaCungCap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo Sản Phẩm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về danh sách", "Index", null, new { @class = "btn btn-secondary" })
</div>

<style>
    .col-md-2 {
        max-width: 30%
    }

    body {
        background-color: #f4f7fa;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #333;
    }

    .page-title {
        text-align: center;
        margin-bottom: 20px;
        font-size: 32px;
        color: #333;
    }

    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
        color: #555;
    }

    .form-control {
        border-radius: 5px;
        border: 1px solid #ccc;
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);
        transition: border-color 0.3s;
    }

        .form-control:focus {
            border-color: #007bff;
            outline: none;
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
        }

    .btn {
        padding: 10px 15px;
        border-radius: 5px;
        color: white;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s, transform 0.2s;
    }

    .btn-primary {
        background-color: #007bff;
    }

    .btn-secondary {
        background-color: #6c757d;
    }

    .btn:hover {
        opacity: 0.9;
        transform: translateY(-1px);
    }

    .text-danger {
        color: #dc3545;
    }
</style>

OnDoanThuan/CNPMNC_Giao/CNPMNC_Giao/Areas/Admin/Views/SanPhams/Details.cshtml
@model CNPMNC_Giao.Models.SanPham

@{
    ViewBag.Title = "Details";
}

<style>
    <style >
    /* General body styling */
    body {
        background-color: #f8f9fa;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #333;
    }

    /* Container for the details */
    dl.dl-horizontal {
        width: 80%;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color: #2c3e50;
        margin-bottom: 30px;
        font-size: 2rem;
    }

    /* Label styling */
    dt {
        font-weight: bold;
        color: #34495e;
        padding-bottom: 10px;
        width: 25%;
        float: left;
        text-align: right;
        margin-right: 20px;
    }

    /* Display value styling */
    dd {
        padding-bottom: 10px;
        margin-left: 0;
        width: 70%;
        float: left;
        text-align: left;
        color: #7f8c8d;
    }

    /* Clear floats after each dt/dd pair */
    dl:after {
        content: "";
        display: table;
        clear: both;
    }

    /* Button and link styling */
    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        text-decoration: none;
        color: #3498db;
        font-weight: 500;
        margin-right: 15px;
        transition: color 0.3s ease;
    }

        a:hover {
            color: #2980b9;
        }

        /* Button styling */
        a.btn-default {
            background-color: #3498db;
            color: white;
            border: none;
            padding: 10px 25px;
            font-size: 1rem;
            border-radius: 25px;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.2s ease;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

            /* Button hover effect */
            a.btn-default:hover {
                background-color: #2980b9;
                transform: translateY(-1px);
            }

            /* Button active effect */
            a.btn-default:active {
                transform: translateY(0);
            }
</style>

<h2>Thông tin chi tiết</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTienMoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaTienMoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTienCu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaTienCu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaCungCap.TenNhaCungCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaCungCap.TenNhaCungCap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VatLieu.TenVatlieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VatLieu.TenVatlieu)
        </dd>
        <h4>Kích cỡ:</h4>
        <ul>
            @foreach (var kichCo in ViewBag.KichCos)
            {
                <li>Kích cỡ: @kichCo.SoKichCo - Số lượng: @kichCo.SoLuong</li>
            }
        </ul>
    </dl>
</div>
@*<div>
    <h4>Kích Cỡ</h4>
    @Html.DropDownList("KichCoDropdown", (SelectList)ViewBag.KichCos, "Chọn Kích Cỡ", new { @class = "form-control" })
</div>

<div>
    <a href="@Url.Action("TaoKichCo", "SanPhams", new { id = Model.MaSanPham })" class="btn btn-primary">Tạo Kích Cỡ Mới</a>
</div>*@
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaSanPham }) |
    @Html.ActionLink("Trở về danh sách", "Index")
</p>

OnDoanThuan/CNPMNC_Giao/CNPMNC_Giao/Areas/Admin/Views/SanPhams/TaoKichCo.cshtml
@model CNPMNC_Giao.Models.KichCo

@{
    ViewBag.Title = "Tạo Kích Cỡ";
}

<h2>Tạo Kích Cỡ</h2>

@using (Html.BeginForm("TaoKichCo", "SanPhams", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.MaSanPham, "Chọn Sản Phẩm:")
        @Html.DropDownList("MaSanPham", new SelectList(ViewBag.SanPhams, "MaSanPham", "TenSanPham"), "Chọn sản phẩm", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MaSanPham)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SoKichCo)
        @Html.TextBoxFor(m => m.SoKichCo, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SoKichCo)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SoLuong)
        @Html.TextBoxFor(m => m.SoLuong, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SoLuong)
    </div>

    <button type="submit" class="btn btn-primary">Tạo Kích Cỡ</button>
}